### ISSUE TITLE
在npm install的时候出现warn

### ISSUE THREAD

**Issue by roy2651** [demopark/electron-api-demos-Zh_CN#1]
npm WARN eslint-config-standard@6.2.1 requires a peer of eslint@>=3.8.1 but none
 was installed.
npm WARN eslint-config-standard@6.2.1 requires a peer of eslint-plugin-promise@>
=3.3.0 but none was installed.
npm WARN eslint-config-standard@6.2.1 requires a peer of eslint-plugin-standard@
>=2.0.0 but none was installed.

**Comment by demopark** [comment]
node v6.11.0
npm 3.10.10

测试并未出现你说的问题
