### ISSUE TITLE
windows 10平台通知无效

### ISSUE THREAD

**Issue by xiubooo** [demopark/electron-api-demos-Zh_CN#11]
* What operating system are you using? 
* What version of Node.js is on your system?
windows10系统,通知示例无效.

**Comment by xiubooo** [comment]
nodejs version:10.9.0

**Comment by demopark** [comment]
@xiubooo 
请参见 API 文档
https://electronjs.org/docs/tutorial/notifications#通知-windows-linux-macos
Windows 10 appids 相关内容
