### ISSUE TITLE
tray 托盘 意外退出

### ISSUE THREAD

**Issue by jjeejj** [demopark/electron-api-demos-Zh_CN#12]
* 您使用什么操作系统? 
   MacOS Sierra  10.12.6
* 您的系统上有哪个版本的 Node.js?
   v10.0.0

在 tray   那一章节，显示完tray 后，用菜单点击移除后，会使应用崩溃的
![tray](https://user-images.githubusercontent.com/15176971/45936636-8d154000-bfeb-11e8-89f6-2b6e34b7281c.gif)

**Comment by demopark** [comment]
@jjeejj 已修正 Thanks

**Comment by jjeejj** [comment]
@demopark  我看了 你提交的那个 [commit](https://github.com/demopark/electron-api-demos-Zh_CN/commit/669e26c7ec80a4aee150e7c196105782ed4605c0)

但是没看懂，为什么 `ipc.send('remove-tray')` 移到下面就可以了？  这样写的原因是什么呢？ 

我刚才测试了一下，还是会意外退出的呢？

**Comment by jjeejj** [comment]
@demopark  我找到原因了，这是一个官方的 bug , https://github.com/electron/electron/pull/14347

现在已经被解决了，只要执行 `npm update electron` 命令升级一下就可以了 ,升级到 ** ^2.0.11**
