### ISSUE TITLE
测试环境下，获取屏幕信息模块报错

### ISSUE THREAD

**Issue by imvicchen** [demopark/electron-api-demos-Zh_CN#30]
* 您使用什么操作系统? 
windows

* 您使用哪个版本的 Node.js?
v12.16.1

npm run dev
测试环境下，获取屏幕信息模块报错
Cannot read property 'getPrimaryDisplay' of undefined

**Comment by demopark** [comment]
@imvicchen fixed. 7 以后 renderer process 访问 main process 需使用 remote modules
