### ISSUE TITLE
崩溃无法重载

### ISSUE THREAD

**Issue by YosamYang** [demopark/electron-api-demos-Zh_CN#33]
* 您使用什么操作系统?  Windows 10
* 您使用哪个版本的 Node.js? 12.18.4
![image](https://user-images.githubusercontent.com/34182461/99636947-1cf58e00-2a7f-11eb-8a93-28f49aaaecb0.png)

**Comment by demopark** [comment]
无报错信息无法处理,如遇需要reopen issues
