### ISSUE TITLE
中文文档，难道是使用Google 翻译？

### ISSUE THREAD

**Issue by web1992** [demopark/electron-api-demos-Zh_CN#7]
>**这中文文档读着一股机器翻译的味道。。。**

>截图
![image](https://user-images.githubusercontent.com/6828647/40533937-df46c6ec-6036-11e8-8cc5-a228df7088b7.png)

**Comment by demopark** [comment]
这是 API DEMO 不是中文文档, 有兴趣可以 Fork 参与翻译
